# Generated by Django 5.0.4 on 2024-05-20 08:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStartap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='startap_category/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'bmp'])], verbose_name='Картинка')),
                ('slug', models.SlugField(blank=True, default='', max_length=40, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='CommentsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, max_length=300, verbose_name='дата и время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Startap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Местоположение')),
                ('deposit_amount', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, verbose_name='Сумма вклада')),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='startap_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='startap_avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Аватарка')),
                ('data', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.categorystartap', verbose_name='Категория')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Стартап',
                'verbose_name_plural': 'Стартапы',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='LikeStartap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('startap', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.startap', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Активнность лайка',
                'verbose_name_plural': 'Активнность лайка',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FilesStartap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='startap_files/')),
                ('startap', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.startap', verbose_name='Стартап')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('id',),
            },
        ),
    ]
