# Generated by Django 5.0.1 on 2024-01-14 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, unique=True, verbose_name='Наименование')),
                ('image', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Картинка')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, default='', verbose_name='Цена')),
                ('image', models.TextField(blank=True, default='', verbose_name='Картинка URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активеность объявления')),
                ('category', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.categoryitem', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('is_active', '-title'),
            },
        ),
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, max_length=300, verbose_name='дата и время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активеность')),
                ('author', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('article', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.item', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
