# Generated by Django 5.0.1 on 2024-01-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актвеность'),
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активнность лайка')),
                ('author', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('item', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.item', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Активнность лайка',
                'verbose_name_plural': 'Активнность лайка',
                'ordering': ('-item',),
            },
        ),
    ]
