# Generated by Django 5.0.1 on 2024-01-22 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Название')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, max_length=300, verbose_name='дата и время создания')),
            ],
        ),
    ]
