# Generated by Django 5.0.4 on 2024-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_images_categorystartap_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystartap',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=40, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='categorystartap',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True, verbose_name='Наименование'),
        ),
    ]
