# Generated by Django 5.0.4 on 2024-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_filesstartap_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesstartap',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Название Файла'),
        ),
    ]
