# Generated by Django 5.0.4 on 2024-05-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_filesstartap_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesstartap',
            name='title',
        ),
    ]
