# Generated by Django 5.0.4 on 2024-05-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_likestartap'),
    ]

    operations = [
        migrations.AddField(
            model_name='startap',
            name='like_count',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='Количество лайков'),
        ),
        migrations.DeleteModel(
            name='LikeStartap',
        ),
    ]
