# Generated by Django 5.0.4 on 2024-05-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_startap_like_count_delete_likestartap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startap',
            name='like_count',
        ),
        migrations.CreateModel(
            name='LikeStartap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активнность лайка')),
                ('author', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('startap', models.ForeignKey(blank=True, default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='django_app.startap', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Активнность лайка',
                'verbose_name_plural': 'Активнность лайка',
                'ordering': ('-id',),
            },
        ),
    ]
