# Generated by Django 5.0.4 on 2024-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorystartap',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='filesstartap',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='startap_files/'),
        ),
    ]
