# Generated by Django 5.0.4 on 2024-05-01 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_startap_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='startap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='startap_avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Аватарка'),
        ),
    ]
