# Generated by Django 5.0.4 on 2024-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_startap_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesstartap',
            name='title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Название Файла'),
        ),
    ]
