# Generated by Django 5.0.4 on 2024-05-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_remove_filesstartap_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeStartap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, verbose_name='Количество лайков')),
                ('startap', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.startap', verbose_name='Стартап')),
            ],
        ),
    ]
