# Generated by Django 5.0.4 on 2024-05-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_remove_startap_like_count_likestartap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likestartap',
            name='is_like',
        ),
    ]
